[package]
name = "rust1"
version = "0.1.0"
authors = ["Adrian Thurston <thurston@colm.net>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
